sudo: false
language: ruby
bundler_args: --without development
env:
  global:
    - JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
    - _JAVA_OPTIONS=
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.1.2.0
  - jruby-9.1.8.0

before_install: gem install bundler -v 1.12.5

cache: bundler
